# Generated by Django 4.0.5 on 2022-06-09 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('screenshot', models.ImageField(upload_to='screenshots/')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('published', models.DateTimeField(default=datetime.datetime(2022, 6, 9, 18, 36, 14, 616227))),
            ],
        ),
    ]
