# Generated by Django 4.0.5 on 2022-06-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_alter_pc_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='pc',
            name='is_exhibition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='text_de',
            field=models.TextField(default='text_de', max_length=20000),
        ),
        migrations.AddField(
            model_name='video',
            name='text_en',
            field=models.TextField(default='text_en', max_length=20000),
        ),
    ]
