# Generated by Django 4.0.5 on 2022-06-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_remove_video_subtitle_pc_is_exhibition_video_text_de_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.AddField(
            model_name='video',
            name='title_de',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='video',
            name='title_en',
            field=models.CharField(default='', max_length=200),
        ),
    ]
