# Generated by Django 4.0.5 on 2022-06-28 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_remove_video_title_video_title_de_video_title_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='ip_address',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('/^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?).(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?).(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?).(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$', 'Keine Gültige IP-Adresse')]),
        ),
        migrations.AlterField(
            model_name='video',
            name='text_de',
            field=models.TextField(default=None, max_length=20000),
        ),
        migrations.AlterField(
            model_name='video',
            name='text_en',
            field=models.TextField(default=None, max_length=20000),
        ),
        migrations.AlterField(
            model_name='video',
            name='title_de',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='title_en',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
