# Generated by Django 4.0.5 on 2022-07-06 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0009_alter_pc_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc',
            name='is_exhibition',
        ),
    ]
