# Generated by Django 4.0.5 on 2022-07-07 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0010_remove_pc_is_exhibition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc',
            name='is_active',
        ),
    ]
