# Generated by Django 4.0.5 on 2022-08-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0011_remove_pc_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='is_expo_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
