# Generated by Django 4.1.1 on 2022-09-22 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0012_pc_is_expo_client_alter_video_screenshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='Videos',
            field=models.ManyToManyField(blank=True, null=True, to='restapi.video'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='ip_address',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.validate_ipv4_address]),
        ),
    ]
