# Generated by Django 4.1.1 on 2022-09-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0013_alter_pc_videos_alter_pc_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='Videos',
            field=models.ManyToManyField(blank=True, to='restapi.video'),
        ),
    ]
