# Generated by Django 4.0.4 on 2022-06-13 09:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 13, 9, 51, 34, 965305, tzinfo=utc)),
        ),
    ]
