# Generated by Django 4.0.5 on 2022-06-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_alter_video_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_name', models.CharField(max_length=50, unique=True)),
                ('ip_address', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('Videos', models.ManyToManyField(to='restapi.video')),
            ],
            options={
                'ordering': ['ip_address'],
            },
        ),
    ]
