# Generated by Django 4.0.5 on 2022-06-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_pc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='ip_address',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
