# Generated by Django 4.0.5 on 2022-06-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_alter_pc_ip_address_alter_video_text_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='ip_address',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
